language: node_js
node_js:
  - "6"
cache:
  directories:
    - "node_modules"
before_script:
  - npm install -g istanbul@1.1.0-alpha.1
  - npm install -g mocha
  - npm install -g codeclimate-test-reporter
after_success:
  - npm run ci
